[package]
name = 'chord-composer-interface'
version = '0.1.2'
authors = ['cj <cj>']
edition = '2018'

[features]
eng = []
pt = []
zhn = []

[dependencies]
chord-composer = '0.3.0'
clap = '2.33.0'
music-timer = '0.1.6'
